//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.Personne_metier = new HashSet<Personne_metier>();
            this.Service = new HashSet<Service>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual ICollection<Personne_metier> Personne_metier { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
